CREATE TABLE bacia (
    idBacia        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(50),
    area           FLOAT(126) NOT NULL,
    perimetro      FLOAT(126) NOT NULL
);

CREATE TABLE rio (
    idRio         INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(50),
    indicativo    VARCHAR(50),
    idBacia       INT REFERENCES bacia(idBacia)
);

CREATE TABLE postopluviometrico (
    idPostoPluviometrico        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome                       VARCHAR(50),
    rua                        VARCHAR(50),
    num                        INT,
    bairro                     VARCHAR(50),
    municipio                  VARCHAR(50),
    estado                     VARCHAR(50),
    idBacia                    INT REFERENCES bacia(idBacia)
);

CREATE TABLE acude (
    idAcude                INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR(50),
    volumeMaximo           FLOAT(126),
    comprimento            FLOAT(126),
    area                   FLOAT(126),
    idRio                  INT REFERENCES rio(idRio)
);

CREATE TABLE cota_area_volume (
    id                    INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cota                  FLOAT(126),
    area                  FLOAT(126),
    volume                FLOAT(126),
    idAcude               INT REFERENCES acude(idAcude)
);

CREATE TABLE usuario (
    matricula        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(50)
);

CREATE TABLE medicaocotadiaria (
    idMedicaoCotaDiaria        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cotaAtual                  INT,
    data                       DATE,
    idAcude                    INT REFERENCES acude(idAcude),
    matricula                  INT REFERENCES usuario(matricula)
);

CREATE TABLE medicaopluviometrica (
    idMedicao            INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data                 DATE
);

CREATE TABLE contribuicao (
    idPostoPluviometrico            INT REFERENCES postopluviometrico(idPostoPluviometrico),
    idAcude                         INT REFERENCES acude(idAcude)
);

CREATE TABLE telefones (
    numero                VARCHAR(20),
    matricula             INT REFERENCES usuario(matricula)
);

CREATE TABLE estacaodequalide (
    idEstacaoQualidade   INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR(50) NOT NULL,
    latitude             VARCHAR2(20),
    longitude            VARCHAR2(20),
    idRio                INT REFERENCES rio(idRio),
    idAcude              INT REFERENCES acude(idAcude),
    data                 DATE,
    pH                   INT,
    turbidez             INT,
    oxigenio             INT,
    alcalinidade         INT
);