/*
Antunes Dantas         antunes.silva@ccc.ufcg.edu.br
Nicácio Oliveira       nicacio.sousa@ccc.ufcg.edu.br
Ivyna Santino          ivyna.alves@ccc.ufcg.edu.br
José Glauber           jose.oliveira@ccc.ufcg.edu.br
Thalyta Fabrine        thalyta.trindade@ccc.ufcg.edu.br
Valter Lucena          valter.lucena@ccc.ufcg.edu.br
*/

CREATE TABLE bacia (
    idBacia        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(128) NOT NULL,
    area           FLOAT(20),
    perimetro      FLOAT(20)
);

CREATE TABLE rio (
    idRio         INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(128),
    indicativo    VARCHAR(10),
    idBacia       INT NOT NULL REFERENCES bacia(idBacia)
);

CREATE TABLE posto_pluviometrico (
    idPostoPluviometrico        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome                       VARCHAR(128) NOT NULL,
    rua                        VARCHAR(128) NOT NULL,
    num                        INT,
    bairro                     VARCHAR(128) NOT NULL,
    municipio                  VARCHAR(128) NOT NULL,
    estado                     VARCHAR(20)  NOT NULL,
    idBacia                    INT NOT NULL REFERENCES bacia(idBacia)
);

CREATE TABLE acude (
    idAcude                INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome                   VARCHAR(128) NOT NULL,
    volumeMaximo           FLOAT(20),
    comprimento            FLOAT(20),
    area                   FLOAT(20),
    idRio                  INT NOT NULL REFERENCES rio(idRio)
);

CREATE TABLE cota_area_volume (
    id                    INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cota                  FLOAT(20),
    area                  FLOAT(20),
    volume                FLOAT(20),
    idAcude               INT NOT NULL REFERENCES acude(idAcude)
);

CREATE TABLE usuario (
    matricula        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome             VARCHAR(128) NOT NULL
);

CREATE TABLE medicao_cota_diaria (
    idMedicaoCotaDiaria        INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cotaAtual                  FLOAT(20),
    data                       DATE,
    idAcude                    INT NOT NULL REFERENCES acude(idAcude),
    matricula                  INT NOT NULL REFERENCES usuario(matricula)
);

CREATE TABLE medicao_pluviometrica (
    idMedicao            INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    data                 DATE
);

CREATE TABLE contribuicao (
    idPostoPluviometrico            INT NOT NULL,
    idAcude                         INT NOT NULL,
    CONSTRAINT PK_CONTRIBUICAO PRIMARY KEY (idPostoPluviometrico, idAcude),
    CONSTRAINT FK_POSTO FOREIGN KEY (idPostoPluviometrico) REFERENCES posto_pluviometrico(idPostoPluviometrico),
    CONSTRAINT FK_ACUDE FOREIGN KEY (idAcude) REFERENCES acude(idAcude)
);

CREATE TABLE telefones_usuario (
    numero                VARCHAR(20) NOT NULL,
    matricula             INT NOT NULL,
    CONSTRAINT PK_TEL_USER PRIMARY KEY (numero, matricula),
    CONSTRAINT FK_TEL_USER FOREIGN KEY (matricula) REFERENCES usuario(matricula)
);



CREATE TABLE estacao_de_qualidade (
    idEstacaoQualidade   INT GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR(50) NOT NULL,
    latitude             VARCHAR2(20),
    longitude            VARCHAR2(20),
    idRio                INT REFERENCES rio(idRio),
    idAcude              INT REFERENCES acude(idAcude),
    data                 DATE,
    pH                   INT,
    turbidez             INT,
    oxigenio             INT,
    alcalinidade         INT
);

BEGIN
  FOR i in 1..31
  LOOP 
    EXECUTE IMMEDIATE ' alter table ' || 'medicao_pluviometrica' || ' add( ' || 'valor_chuva_dia_' || i || ' ' || 'FLOAT(20)' || ' ) ' ;
  END LOOP;
END;