/*Grupo 6: Antunes Dantas da Silva, Nicácio Oliveira de Sousa, Ivyna Rayany Santino, José Glauber Braz, Thalyta Fabrine e Valter Vinicius de Lucena.*/

/*USUARIOS*/
INSERT INTO USUARIO (nome) VALUES ('Antunes');
INSERT INTO USUARIO (nome) VALUES ('Nicácio');
INSERT INTO USUARIO (nome) VALUES ('Ivyna');
INSERT INTO USUARIO (nome) VALUES ('Glauber');
INSERT INTO USUARIO (nome) VALUES ('Thalyta');
INSERT INTO USUARIO (nome) VALUES ('Vinícius');

/*TELEFONES USUARIOS*/
INSERT INTO TELEFONES_USUARIO (NUMERO, MATRICULA) VALUES ('9999-9999', (SELECT matricula FROM usuario WHERE nome='Antunes' ));
INSERT INTO TELEFONES_USUARIO (NUMERO, MATRICULA) VALUES ('8888-8888', (SELECT matricula FROM usuario WHERE nome='Nicácio' ));
INSERT INTO TELEFONES_USUARIO (NUMERO, MATRICULA) VALUES ('7777-7777', (SELECT matricula FROM usuario WHERE nome='Ivyna' ));
INSERT INTO TELEFONES_USUARIO (NUMERO, MATRICULA) VALUES ('6666-6666', (SELECT matricula FROM usuario WHERE nome='Glauber' ));
INSERT INTO TELEFONES_USUARIO (NUMERO, MATRICULA) VALUES ('5555-5555', (SELECT matricula FROM usuario WHERE nome='Thalyta' ));
INSERT INTO TELEFONES_USUARIO (NUMERO, MATRICULA) VALUES ('4444-4444', (SELECT matricula FROM usuario WHERE nome='Vinícius' ));


/*BACIAS*/
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Alto Paraíba'                , 20071.83   , 1077.98 );
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Beberibe'                    , 79.000     , 2077.98 );
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Piranhas-Açu'                , 43681.50   , 43681.50);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Apodi-Mossoró'               , 14.276     , 14.276  );
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Amazônica'                   , 3800000.000, 2077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Tocantins-Araguaia'          , 967059.000 , 3077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Atlântico Nordeste Ocidental', 254100.000 , 2077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Parnaíba'                    , 344112.000 , 3077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Atlântico Nordeste Oriental' , 287348.000 , 3077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('São Francisco'               , 640000.000 , 2077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Atlântico Leste'             , 374677.000 , 1077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Atlântico Sudeste'           , 229972.000 , 1077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Paraná'                      , 879860.000 , 2077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Paraguai'                    , 363442.000 , 2077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Uruguai'                     , 174612.000 , 2077.98);
INSERT INTO BACIA (NOME, AREA, PERIMETRO) VALUES ('Atlântico Sul'               , 185856.000 , 2077.98);



/*RIOS*/
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Beberibe'           , 'B', (SELECT idbacia FROM bacia WHERE nome='Beberibe'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Paraíba'            , 'A', (SELECT idbacia FROM bacia WHERE nome='Alto Paraíba'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('São Francisco'      , 'C', (SELECT idbacia FROM bacia WHERE nome='São Francisco'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Potengi'            , 'D', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Curimataú'          , 'E', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Moçoró'             , 'B', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Pitimbu'            , 'A', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Acauã'              , 'E', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Piranhas'           , 'C', (SELECT idbacia FROM bacia WHERE nome='Piranhas-Açu'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Trairi'                , 'D', (SELECT idbacia FROM bacia WHERE nome='Piranhas-Açu'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Amazonas'           , 'A', (SELECT idbacia FROM bacia WHERE nome='Amazônica'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Negro'              , 'B', (SELECT idbacia FROM bacia WHERE nome='Amazônica'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Solimões'           , 'D', (SELECT idbacia FROM bacia WHERE nome='Amazônica'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Tocantins'          , 'D', (SELECT idbacia FROM bacia WHERE nome='Tocantins-Araguaia'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Araguaia'           , 'A', (SELECT idbacia FROM bacia WHERE nome='Tocantins-Araguaia'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Itacaiunas'         , 'C', (SELECT idbacia FROM bacia WHERE nome='Tocantins-Araguaia'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Gurupi'             , 'B', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Ocidental'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Turiaçu'            , 'C', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Ocidental'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Pericumã'           , 'D', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Ocidental'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Uruçuí-Preto'       , 'D', (SELECT idbacia FROM bacia WHERE nome='Parnaíba'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Gurgueia'           , 'A', (SELECT idbacia FROM bacia WHERE nome='Parnaíba'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Balsas'             , 'B', (SELECT idbacia FROM bacia WHERE nome='Parnaíba'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Jaguaribe'          , 'C', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Oriental'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Caíbaribe'          , 'D', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Oriental'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Cariús'             , 'E', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Oriental'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('São Francisco'      , 'A', (SELECT idbacia FROM bacia WHERE nome='São Francisco'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('das Velhas'         , 'B', (SELECT idbacia FROM bacia WHERE nome='São Francisco'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Carinhanha'         , 'C', (SELECT idbacia FROM bacia WHERE nome='São Francisco'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('De Contas'          , 'D', (SELECT idbacia FROM bacia WHERE nome='Atlântico Leste'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Pardo'              , 'E', (SELECT idbacia FROM bacia WHERE nome='Atlântico Leste'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Mucuri'             , 'C', (SELECT idbacia FROM bacia WHERE nome='Atlântico Leste'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Doce'               , 'D', (SELECT idbacia FROM bacia WHERE nome='Atlântico Sudeste'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Paraíba do SUl'     , 'A', (SELECT idbacia FROM bacia WHERE nome='Atlântico Sudeste'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Ribeira de Iguape'  , 'B', (SELECT idbacia FROM bacia WHERE nome='Atlântico Sudeste'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Paraná'             , 'E', (SELECT idbacia FROM bacia WHERE nome='Paraná'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Tietê'              , 'B', (SELECT idbacia FROM bacia WHERE nome='Paraná'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Iguaçu'             , 'A', (SELECT idbacia FROM bacia WHERE nome='Paraná'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Miranda'            , 'C', (SELECT idbacia FROM bacia WHERE nome='Paraguai'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('São Lourenço'       , 'D', (SELECT idbacia FROM bacia WHERE nome='Paraguai'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Cuiabá'             , 'E', (SELECT idbacia FROM bacia WHERE nome='Paraguai'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Chapecó'            , 'A', (SELECT idbacia FROM bacia WHERE nome='Uruguai'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Uruguai'            , 'B', (SELECT idbacia FROM bacia WHERE nome='Uruguai'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Passo Fundo'        , 'C', (SELECT idbacia FROM bacia WHERE nome='Uruguai'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Itajaí'             , 'E', (SELECT idbacia FROM bacia WHERE nome='Atlântico Sul'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Jacuí'              , 'A', (SELECT idbacia FROM bacia WHERE nome='Atlântico Sul'));
INSERT INTO RIO (NOME, INDICATIVO, IDBACIA) VALUES ('Itajaí-Açu'         , 'C', (SELECT idbacia FROM bacia WHERE nome='Atlântico Sul'));




/*AÇUDES*/
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Bodocongó'          , 1020000        , 411686287.0, 421687.000, (SELECT idrio FROM RIO WHERE nome='Paraíba'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Epitácio Pessoa'    , 411686287.000  , 1686287.000, 411627.000, (SELECT idrio FROM RIO WHERE nome='Paraíba'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Castanhão'          , 6700000000.000 , 6200000.000, 26700000.0, (SELECT idrio FROM RIO WHERE nome='Jaguaribe'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Campo Grande'       , 2700000000.000 , 2357833.246, 170000000 , (SELECT idrio FROM RIO WHERE nome='Piranhas'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Encanto'           , 4700000000.000 , 1345634.344, 523000000 , (SELECT idrio FROM RIO WHERE nome='Piranhas'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Pepta'           , 7700000000.000 , 1346566.345, 8300000000, (SELECT idrio FROM RIO WHERE nome='Piranhas'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Itajá'              , 2700000000.000 , 2355.3453  , 62345000.0, (SELECT idrio FROM RIO WHERE nome='Piranhas'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Mendubim'              , 3700000000.000 , 2220345.234, 43513.2351, (SELECT idrio FROM RIO WHERE nome='Piranhas'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Acari'              , 4000000000.000 , 24343.34442, 1534364.14, (SELECT idrio FROM RIO WHERE nome='Piranhas'));
INSERT INTO ACUDE (NOME, VOLUMEMAXIMO, COMPRIMENTO, AREA, IDRIO) VALUES ('Açude do rio Beberibe', 100000         , 6000000.000, 3415.23434, (SELECT idrio FROM RIO WHERE nome='Beberibe'));



/*ESTAÇÕES DE QUALIDADE*/
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Boqueirão','-7.4994275', '-36.1952624', (SELECT idrio FROM RIO WHERE nome='Paraíba'), (SELECT idacude FROM ACUDE WHERE nome='Epitácio Pessoa'), TO_DATE('2001/03/01 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), 5, 4, 7, 3, 10);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Bodocongó','-7.21412928', '-35.91575142', (SELECT idrio FROM RIO WHERE nome='Paraíba'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), TO_DATE('1999/01/03 07:02:40', 'yyyy/mm/dd hh24:mi:ss'), 5, 3, 7, 4, 5);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Castanhão','-5.4975148', '-38.446833', (SELECT idrio FROM RIO WHERE nome='Jaguaribe'), (SELECT idacude FROM ACUDE WHERE nome='Castanhão'), TO_DATE('1845/06/04 14:23:34', 'yyyy/mm/dd hh24:mi:ss'), 3, 6, 3, 2, 8);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Bodocongó','-7.21412928', '-35.91575142', (SELECT idrio FROM RIO WHERE nome='Paraíba'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), TO_DATE('2018/01/03 07:02:40', 'yyyy/mm/dd hh24:mi:ss'), 5, 3, 10, 4, 5);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Bodocongó','-7.21412928', '-35.91575142', (SELECT idrio FROM RIO WHERE nome='Paraíba'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), TO_DATE('2017/12/29 07:02:40', 'yyyy/mm/dd hh24:mi:ss'), 5, 3, 8, 4, 5);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Campo Grande','-5.8897755', '-35.7761685', (SELECT idrio FROM RIO WHERE nome='Potengi'), (SELECT idacude FROM ACUDE WHERE nome='Campo Grande'), TO_DATE('1845/06/04 14:23:34', 'yyyy/mm/dd hh24:mi:ss'), 3, 6, 3, 2, 8);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Itajá','-5.6426898', '-36.8643804', (SELECT idrio FROM RIO WHERE nome='Piranhas'), (SELECT idacude FROM ACUDE WHERE nome='Itajá'), TO_DATE('1845/06/04 14:23:34', 'yyyy/mm/dd hh24:mi:ss'), 3, 6, 3, 2, 8);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('BeberibeRN','-2.8935386', '-5.2698714', (SELECT idrio FROM RIO WHERE nome='Beberibe'), (SELECT idacude FROM ACUDE WHERE nome='Açude do rio Beberibe'), TO_DATE('2017/01/14 15:00:00', 'yyyy/mm/dd hh24:mi:ss'), 9, 7, 1, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('AcariPiranhas','-2.8935386', '-9.2698714', (SELECT idrio FROM RIO WHERE nome='Piranhas'), (SELECT idacude FROM ACUDE WHERE nome='Acari'), TO_DATE('2017/01/14 12:00:00', 'yyyy/mm/dd hh24:mi:ss'), 4, 7, 3, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('MendubimPiranhas','-7.8935386', '-5.2698714', (SELECT idrio FROM RIO WHERE nome='Piranhas'), (SELECT idacude FROM ACUDE WHERE nome='Mendubim'), TO_DATE('2017/05/15 13:00:00', 'yyyy/mm/dd hh24:mi:ss'), 9, 2, 1, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('ItajáPiranhas','-1.8935386', '-5.2698714', (SELECT idrio FROM RIO WHERE nome='Piranhas'), (SELECT idacude FROM ACUDE WHERE nome='Itajá'), TO_DATE('2017/01/14 14:00:00', 'yyyy/mm/dd hh24:mi:ss'), 8, 7, 1, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('PotejiEncanto','-2.8935386', '-5.2698714', (SELECT idrio FROM RIO WHERE nome='Poteji'), (SELECT idacude FROM ACUDE WHERE nome='Encanto'), TO_DATE('2017/04/10 15:00:00', 'yyyy/mm/dd hh24:mi:ss'), 9, 7, 1, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('PotengiPepta','-3.8935386', '-1.2698714', (SELECT idrio FROM RIO WHERE nome='Potengi'), (SELECT idacude FROM ACUDE WHERE nome='Pepta'), TO_DATE('2017/02/11 11:00:00', 'yyyy/mm/dd hh24:mi:ss'), 1, 5, 2, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Beberibe','-2.8935376', '-6.2698714', (SELECT idrio FROM RIO WHERE nome='Beberibe'), (SELECT idacude FROM ACUDE WHERE nome='Açude do rio Beberibe'), TO_DATE('2017/03/08 15:00:00', 'yyyy/mm/dd hh24:mi:ss'), 8, 7, 1, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Beberibe','-2.8936386', '-7.2698714', (SELECT idrio FROM RIO WHERE nome='Beberibe'), (SELECT idacude FROM ACUDE WHERE nome='Açude do rio Beberibe'), TO_DATE('2017/07/09 15:00:00', 'yyyy/mm/dd hh24:mi:ss'), 4, 7, 1, 3, 7);
INSERT INTO ESTACAO_DE_QUALIDADE (NOME, LATITUDE, LONGITUDE, IDRIO, IDACUDE, DATA, PH, TURBIDEZ, OXIGENIO, ALCALINIDADE, DBO)
VALUES ('Beberibe','-2.8935344', '-9.2698714', (SELECT idrio FROM RIO WHERE nome='Beberibe'), (SELECT idacude FROM ACUDE WHERE nome='Açude do rio Beberibe'), TO_DATE('2017/12/17 15:00:00', 'yyyy/mm/dd hh24:mi:ss'), 2, 7, 1, 3, 7);




/* POSTOS PLUVIOMÉTRICOS */
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('R2D2', 'Aprígio Veloso', 882, 'Universitário', 'Campina Grande', 'Paraíba', (SELECT idbacia FROM bacia WHERE nome='Alto Paraíba'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Chewbacca', 'Aprígio Veloso', 882, 'Universitário', 'Campina Grande', 'Paraíba', (SELECT idbacia FROM bacia WHERE nome='Atlântico Nordeste Oriental'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Pato no Tucupi', 'Aprígio Veloso', 882, 'Universitário', 'Campina Grande', 'Paraíba', (SELECT idbacia FROM bacia WHERE nome='Alto Paraíba'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Cubati', 'Aprígio Veloso', 882, 'Universitário', 'Campina Grande', 'Paraíba', (SELECT idbacia FROM bacia WHERE nome='Alto Paraíba'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Posto 1 do RN', 'Michel Temer', 13, 'Catolé', 'Natal', 'Rio Grande do Norte', (SELECT idbacia FROM bacia WHERE nome='São Francisco'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Posto 3 do RN', 'João Amaro', 21, 'Universitário', 'Caicó', 'Rio Grande do Norte', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Posto 2 do RN', 'Rua do Paralelepípedo', 42, 'Centro', 'Apodi', 'Rio Grande do Norte', (SELECT idbacia FROM bacia WHERE nome='Piranhas-Açu'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Posto 4 do RN', 'Rua Asfaltada', 24, 'Zepa', 'Natal', 'Rio Grande do Norte', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Posto 5 do RN', 'Marques de Evaldo', 2, 'Projetado', 'Caicó', 'Rio Grande do Norte', (SELECT idbacia FROM bacia WHERE nome='Apodi-Mossoró'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('Posto 6 do RN', 'Rua do Paralelepípedo', 42, 'Palmeira', 'Natal', 'Rio Grande do Norte', (SELECT idbacia FROM bacia WHERE nome='Beberibe'));
INSERT INTO POSTO_PLUVIOMETRICO (NOME, RUA, NUM, BAIRRO, MUNICIPIO, ESTADO, IDBACIA)
VALUES ('BB8', 'Assis Pereira', 1002, 'Centro', 'Bonito de Santa Fé', 'Paraíba', (SELECT idbacia FROM bacia WHERE nome='Piranhas-Açu'));


/*MEDICAO PLUVIOMETRICA
*/
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2017/02/28 05:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Nicácio'), 6.0, 1.0, 0.0, 0.9, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='BB8'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2017/03/30 05:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Nicácio'), 6.0, 1.0, 0.2, 0.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='BB8'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/06/30 12:55:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Nicácio'), 6.0, 1.0, 6.0, 0.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='Posto 3 do RN'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/01/31 12:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Nicácio'), 6.0, 1.0, 0.0, 9.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='Posto 1 do RN'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/07/10 12:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Thalyta'), 6.0, 1.0, 0.0, 6.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='Posto 1 do RN'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2017/02/12 12:00:45', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Antunes'), 6.0, 1.0, 0.0, 9.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='Posto 1 do RN'));

INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/01/31 12:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Thalyta'), 6.0, 1.0, 0.6, 0.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='Chewbacca'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/06/05 12:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Thalyta'), 6.0, 1.0, 0.6, 6.0, 9.0, 2.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='Chewbacca'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/05/05 14:45:23', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Glauber'), 6.0, 1.0, 0.0, 2.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='R2D2'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/01/31 14:45:23', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Antunes'), 6.0, 1.0, 0.0, 4.0, 9.0, 0.3, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='R2D2'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/02/25 12:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Glauber'), 6.0, 1.0, 4.0, 15.0, 9.0, 8.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.2, 2.0, 0.6, 0.0, 0.0, 0.0, 0.0, 1.1, 2.0, 11.5,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='BB8'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/05/05 14:45:23', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Vinícius'), 6.0, 1.0, 0.0, 0.0, 9.0, 0.0, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.6, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.1, 11.0, 11.0,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='R2D2'));
INSERT INTO MEDICAO_PLUVIOMETRICA (DATA, MATRICULA, VALOR_CHUVA_DIA_1, VALOR_CHUVA_DIA_2,
      VALOR_CHUVA_DIA_3, VALOR_CHUVA_DIA_4, VALOR_CHUVA_DIA_5, VALOR_CHUVA_DIA_6,VALOR_CHUVA_DIA_7,
      VALOR_CHUVA_DIA_8, VALOR_CHUVA_DIA_9, VALOR_CHUVA_DIA_10, VALOR_CHUVA_DIA_11, VALOR_CHUVA_DIA_12,
      VALOR_CHUVA_DIA_13, VALOR_CHUVA_DIA_14, VALOR_CHUVA_DIA_15, VALOR_CHUVA_DIA_16, VALOR_CHUVA_DIA_17,
      VALOR_CHUVA_DIA_18, VALOR_CHUVA_DIA_19, VALOR_CHUVA_DIA_20, VALOR_CHUVA_DIA_21, VALOR_CHUVA_DIA_22,
      VALOR_CHUVA_DIA_23, VALOR_CHUVA_DIA_24, VALOR_CHUVA_DIA_25, VALOR_CHUVA_DIA_26, VALOR_CHUVA_DIA_27,
      VALOR_CHUVA_DIA_28, VALOR_CHUVA_DIA_29, VALOR_CHUVA_DIA_30, VALOR_CHUVA_DIA_31, IDPOSTOPLUVIOMETRICO)
VALUES ((TO_DATE('2018/10/17 12:00:00', 'yyyy/mm/dd hh24:mi:ss')), (SELECT matricula FROM usuario WHERE nome='Vinícius'), 6.5, 0.0, 6.0, 1.0, 9.8, 8.1, 0.0,
      0.0, 16.1, 4.2, 16.5, 0.2, 49.5, 25.3, 1.0, 7.0, 7.2, 2.0, 0.0, 6.0, 0.0, 0.0, 0.0, 1.1, 2.0, 11.5,
      0.0, 1.0, 0.0, 0.0, 0.0, (SELECT idPostoPluviometrico FROM POSTO_PLUVIOMETRICO WHERE nome='BB8'));




/*MEDICÃO COTA DIÁRIA*/
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.8045, TO_DATE('2000/01/01 06:06:06', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Epitácio Pessoa'), (SELECT matricula FROM usuario WHERE nome='Antunes' ));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.8021, TO_DATE('2000/01/02 04:06:04', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Epitácio Pessoa'), (SELECT matricula FROM usuario WHERE nome='Antunes' ));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.80123, TO_DATE('2000/01/03 05:05:06', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Epitácio Pessoa'), (SELECT matricula FROM usuario WHERE nome='Antunes' ));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.90213, TO_DATE('2000/02/08 09:02:06', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Epitácio Pessoa'), (SELECT matricula FROM usuario WHERE nome='Antunes' ));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.70123, TO_DATE('2000/01/01 06:06:01', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), (SELECT matricula FROM usuario WHERE nome='Nicácio'));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.70124, TO_DATE('2000/01/02 05:01:00', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), (SELECT matricula FROM usuario WHERE nome='Nicácio'));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.70125, TO_DATE('2000/01/03 08:02:20', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), (SELECT matricula FROM usuario WHERE nome='Nicácio'));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.70125, TO_DATE('2001/02/15 07:24:14', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Bodocongó'), (SELECT matricula FROM usuario WHERE nome='Nicácio'));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.40123, TO_DATE('2000/01/01 09:06:21', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Castanhão'), (SELECT matricula FROM usuario WHERE nome='Ivyna'));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.40122, TO_DATE('2000/01/02 10:00:34', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Castanhão'), (SELECT matricula FROM usuario WHERE nome='Ivyna'));
INSERT INTO MEDICAO_COTA_DIARIA (COTAATUAL, DATA, IDACUDE, MATRICULA)
VALUES (0.40121, TO_DATE('2000/01/03 11:00:06', 'yyyy/mm/dd hh24:mi:ss'), (SELECT idacude FROM ACUDE WHERE nome='Castanhão'), (SELECT matricula FROM usuario WHERE nome='Ivyna'));

/* CONTRIBUIÇÕES */
INSERT INTO CONTRIBUICAO (IDPOSTOPLUVIOMETRICO, IDACUDE)
VALUES ((SELECT idpostopluviometrico FROM posto_pluviometrico WHERE nome='R2D2'), (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO CONTRIBUICAO (IDPOSTOPLUVIOMETRICO, IDACUDE)
VALUES ((SELECT idpostopluviometrico FROM posto_pluviometrico WHERE nome='Chewbacca'), (SELECT idacude FROM acude WHERE nome='Epitácio Pessoa'));
INSERT INTO CONTRIBUICAO (IDPOSTOPLUVIOMETRICO, IDACUDE)
VALUES ((SELECT idpostopluviometrico FROM posto_pluviometrico WHERE nome='Pato no Tucupi'), (SELECT idacude FROM acude WHERE nome='Castanhão'));

/*COTA AREA VOLUME*/
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2367, 13.500, 2200.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2333, 13.500, 2100.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2357, 13.600, 2400.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2357, 13.600, 2400.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2357, 13.600, 2400.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2357, 13.600, 2400.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2357, 13.600, 2400.5, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.2357, 13.600, 2400.10, (SELECT idacude FROM acude WHERE nome='Bodocongó'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.4567, 11.600, 500.55, (SELECT idacude FROM acude WHERE nome='Epitácio Pessoa'));
INSERT INTO COTA_AREA_VOLUME (COTA, AREA, VOLUME, IDACUDE) VALUES (0.3467, 12.300, 100.45, (SELECT idacude FROM acude WHERE nome='Castanhão'));
